name: smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:

    strategy:
      matrix: 
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2.4.1
      with:
        node-version: '14'
        cache: 'npm'

    - name: install
      run: |
        npm i

    - name: build
      run: |
        npm run build

    - name: test
      run: |
        npm run test
